name: CI on master

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository…
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install Zig 0.14.1
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.14.1

      - name: Full build…
        run: make full-build
